name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create JS file (bash)
        shell: bash
        run: |
          echo 'console.log("Hello World!");' > app.js

      - name: Show file content (debug)
        shell: bash
        run: |
          cat app.js

      - name: Run Node.js file
        run: node app.js


  system-info:
    runs-on: windows-latest

    steps:
      - name: OS & Runner info
        run: |
          systeminfo

      - name: Node & npm versions
        run: |
          node --version
          npm --version

      - name: CPU info
        run: |
          wmic cpu get name

      - name: Memory info
        run: |
          wmic OS get TotalVisibleMemorySize,FreePhysicalMemory
