name: My first workflow
on: workflow_dispatch
jobs:
    my-first-job:
        runs-on: window
        steps:
            - name: List all Files
              run : ls -a
            - name: Print Working Directory
              run : pwd
            - name: Create JS Files
              run : echo 'console.log("Hello  World!");' > app.js
            - name : List all Files
              run : ls -a
            - name : Run Node.js Files
              run: node app.js
